export const modules = [
  {
    id: 1,
    title: "Fundamentos de la Sabiduría",
    author: "Maestros Ancestrales",
    description:
      "Introducción a los conceptos básicos de la sabiduría universal y el conocimiento ancestral.",
    progress: 85,
    status: "in-progress",
    duration: "2 horas",
    chapters: 8,
    locked: false,
    publishedYear: "2024",
    rating: 4.8,
    coverUrl: "/uno.jpg",
    content: `...`,
  },
  {
    id: 2,
    title: "Meditación y Mindfulness",
    author: "Guías Espirituales",
    progress: 60,
    status: "in-progress",
    duration: "3 horas",
    chapters: 12,
    locked: false,
    publishedYear: "2024",
    rating: 4.9,
    coverUrl: "/dos.jpg",
    content: `...`,
  },
];
