// export enum NotificationType {
//   WELCOME = 'WELCOME',
//   LOGIN_SUCESS = 'LOGIN_SUCCESS',
//   MEMBERSHIP_EXPIRING = 'MEMBERSHIP_EXPIRING',
//   COMPANY_SUBSCRIPTION_EXPIRING = 'COMPANY_SUBSCRIPTION_EXPIRING',
//   PRODUCT_LOW_STOCK = 'PRODUCT_LOW_STOCK',  
//   SALES_SUMMARY = 'SALES_SUMMARY',
// }
